import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import Indice from "@/components/Indice";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Nyrule RPG",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Indice />
				<main>{ children }</main>
			</body>
		</html>
	);
}
